version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=aA123456
      - MSSQL_PID=Express
    ports:
      - "1488:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost,1433 -U sa -P aA123456 -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "1489:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 2

  profilesapi:
    build:
      context: ./ProfilesApi
      dockerfile: Dockerfile
    container_name: profilesapi
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__sqlConnection=Data Source=sqlserver;Initial Catalog=InnoTest;User ID=sa;Password=aA123456;TrustServerCertificate=True;MultipleActiveResultSets=true
      - Serilog__WriteTo__0__Args__databaseUrl=mongodb://mongodb:27017/serilogdb
    depends_on:
      sqlserver:
        condition: service_healthy
      mongodb:
        condition: service_healthy 