// <auto-generated />
using System;
using Infrastructure.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ProfilesApiDbContext))]
    partial class ProfilesApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AdminDateBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdminFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Office_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Profile_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DoctorCareerStartYear")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DoctorDateBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Office_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Profile_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Specialization_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            DoctorCareerStartYear = new DateTime(2001, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorDateBirth = new DateTime(2001, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorFirstName = "Pasha",
                            DoctorLastName = "Swagovich",
                            DoctorMiddleName = "Andreevich",
                            Office_ID = new Guid("00000000-0000-0000-0000-000000000000"),
                            Profile_ID = new Guid("00000000-0000-0000-0000-000000000000"),
                            Specialization_ID = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa7"),
                            DoctorCareerStartYear = new DateTime(2001, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorDateBirth = new DateTime(2001, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorFirstName = "Pasha",
                            DoctorLastName = "Swagovich",
                            DoctorMiddleName = "Andreevich",
                            Office_ID = new Guid("00000000-0000-0000-0000-000000000000"),
                            Profile_ID = new Guid("00000000-0000-0000-0000-000000000000"),
                            Specialization_ID = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa8"),
                            DoctorCareerStartYear = new DateTime(2001, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorDateBirth = new DateTime(2001, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorFirstName = "Pasha",
                            DoctorLastName = "Swagovich",
                            DoctorMiddleName = "Andreevich",
                            Office_ID = new Guid("00000000-0000-0000-0000-000000000000"),
                            Profile_ID = new Guid("00000000-0000-0000-0000-000000000000"),
                            Specialization_ID = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PatientDateBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Profile_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
